#!/usr/bin/env python3
"""Regenerate frontend/src/pages/sim/cellularImsErrorCodes.ts from errors.rs.

The backend `errors::code` table is the single source of truth. The frontend
keeps an exact copy so the UI can match codes by equality instead of
substring. `test_ims_error_code_contract.py` fails if the two drift apart.
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
ERRORS = ROOT / "backend/src/connectivity/modems/ims/cellular_ims/errors.rs"
TARGET = ROOT / "frontend/src/pages/sim/cellularImsErrorCodes.ts"
CONST_RE = re.compile(r'pub const ([A-Z0-9_]+): &str\s*=\s*\n?\s*"([^"]+)"\s*;', re.MULTILINE)


def render() -> str:
    codes = sorted({value for _, value in CONST_RE.findall(ERRORS.read_text(encoding="utf8"))})
    body = "\n".join(f"  '{code}'," for code in codes)
    return (
        "// Generated by .github/scripts/gen_cellular_ims_error_codes.py from\n"
        "// backend/src/connectivity/modems/ims/cellular_ims/errors.rs. Do not edit;\n"
        "// test_ims_error_code_contract.py fails when this list drifts.\n"
        "export const CELLULAR_IMS_ERROR_CODES = [\n"
        f"{body}\n"
        "] as const\n"
        "\n"
        "export type CellularImsErrorCode = (typeof CELLULAR_IMS_ERROR_CODES)[number]\n"
    )


if __name__ == "__main__":
    content = render()
    if "--check" in sys.argv:
        sys.exit(0 if TARGET.read_text(encoding="utf8") == content else 1)
    TARGET.write_text(content, encoding="utf8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)}")
