//! Boot-time preparation for the QCM410 secondary QMI endpoint.

use anyhow::Result;

use super::secondary_qmi;

const STATE_DIR: &str = "/run/simadmin";
const UDEV_RULE_PATH: &str = "/run/udev/rules.d/99-simadmin-secondary-qmi-runtime.rules";

fn udev_rules(port_name: &str, netdev: Option<&str>) -> Vec<String> {
    let mut rules = vec![format!(
        "SUBSYSTEM==\"wwan\", KERNEL==\"{port_name}\", ENV{{ID_MM_PORT_IGNORE}}=\"1\""
    )];
    if let Some(netdev) = netdev {
        rules.push(format!(
            "SUBSYSTEM==\"net\", KERNEL==\"{netdev}\", ENV{{ID_MM_PORT_IGNORE}}=\"1\""
        ));
    }
    rules
}

async fn reconcile_udev_rules(path: &str, rules: &[String]) {
    let mut changed = false;
    if rules.is_empty() {
        if std::path::Path::new(path).exists() {
            match std::fs::remove_file(path) {
                Ok(()) => {
                    println!("removed stale {path}");
                    changed = true;
                }
                Err(error) => eprintln!("could not remove {path}: {error}"),
            }
        }
    } else {
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let body = format!(
            "# Generated by `simadmin device-init`.\n\
             # These endpoints carry IMS/VoLTE and must stay under SimAdmin's control;\n\
             # ModemManager must not claim them as extra modem ports.\n{}\n",
            rules.join("\n")
        );
        match std::fs::write(path, body) {
            Ok(()) => {
                println!("wrote {path}");
                changed = true;
            }
            Err(error) => eprintln!("could not write {path}: {error}"),
        }
    }

    if !changed {
        return;
    }
    let _ = tokio::process::Command::new("udevadm")
        .args(["control", "--reload-rules"])
        .status()
        .await;
    for subsystem in ["wwan", "net"] {
        let _ = tokio::process::Command::new("udevadm")
            .args(["trigger", &format!("--subsystem-match={subsystem}")])
            .status()
            .await;
    }
}

/// Prepare every QCM410 baseband's SimAdmin-owned QMI endpoint.
pub async fn run(write_udev_rule: bool, dry_run: bool) -> Result<()> {
    if !dry_run && secondary_qmi::purge_legacy_rpmsg_module().await {
        println!("device-init(qcm410): removed the legacy multi-port RPMSG module");
    }

    let primaries = if dry_run {
        secondary_qmi::discover_primary_qmi_ports()
    } else {
        secondary_qmi::wait_for_primary_qmi_ports(secondary_qmi::PRIMARY_PORT_WAIT).await
    };
    if primaries.is_empty() {
        if write_udev_rule && !dry_run {
            reconcile_udev_rules(UDEV_RULE_PATH, &[]).await;
        }
        println!("device-init(qcm410): no QMI control port found; nothing to do");
        if !dry_run {
            notify_ready("no QMI control port; UE-native paths unavailable").await;
        }
        return Ok(());
    }

    let mut rules = Vec::new();
    let mut prepared = Vec::new();
    for primary in &primaries {
        if dry_run {
            match secondary_qmi::baseband_key_for_device(primary) {
                Ok(baseband) => {
                    println!("would prepare an IMS endpoint for {primary} (baseband {baseband})")
                }
                Err(error) => println!("would skip {primary}: {error}"),
            }
            continue;
        }
        match secondary_qmi::ensure_endpoint(primary).await {
            Ok(endpoint) => {
                println!(
                    "secondary QMI ready: {} -> {} (channel {}, baseband {}, mode {:?})",
                    primary,
                    endpoint.device_path,
                    endpoint.channel,
                    endpoint.remoteproc,
                    endpoint.open_mode
                );
                rules.extend(udev_rules(&endpoint.port_name, endpoint.netdev.as_deref()));
                prepared.push(endpoint);
            }
            Err(error) => eprintln!("secondary QMI unavailable for {primary}: {error}"),
        }
    }

    if dry_run {
        return Ok(());
    }
    if write_udev_rule {
        reconcile_udev_rules(UDEV_RULE_PATH, &rules).await;
    }

    publish_endpoint_state(&prepared)?;
    notify_ready(&format!(
        "DATA6 stock RPMSG initialized at {}",
        prepared
            .first()
            .map(|endpoint| endpoint.device_path.as_str())
            .unwrap_or("unavailable")
    ))
    .await;

    println!(
        "device-init(qcm410): {} of {} baseband(s) have an IMS endpoint",
        prepared.len(),
        primaries.len()
    );
    if prepared.is_empty() {
        println!("device-init(qcm410): DATA6 unavailable; UE-native cellular paths unavailable");
        return Ok(());
    }

    let mut monitors = tokio::task::JoinSet::new();
    for endpoint in prepared {
        monitors.spawn(async move { secondary_qmi::hold_endpoint(&endpoint).await });
    }
    match monitors.join_next().await {
        Some(Ok(Err(error))) => Err(anyhow::anyhow!(error)),
        Some(Err(error)) => Err(anyhow::anyhow!("secondary QMI monitor failed: {error}")),
        Some(Ok(Ok(()))) => Err(anyhow::anyhow!("secondary QMI monitor exited unexpectedly")),
        None => Err(anyhow::anyhow!("secondary QMI monitor was not started")),
    }
}

fn publish_endpoint_state(prepared: &[secondary_qmi::SecondaryQmiEndpoint]) -> Result<()> {
    let _ = std::fs::create_dir_all(STATE_DIR);
    let payload = serde_json::to_string_pretty(
        &prepared
            .iter()
            .map(|endpoint| {
                serde_json::json!({
                    "baseband": endpoint.remoteproc,
                    "channel": endpoint.channel,
                    "port_name": endpoint.port_name,
                    "device_path": endpoint.device_path,
                    "netdev": endpoint.netdev,
                    "driver": endpoint.driver,
                })
            })
            .collect::<Vec<_>>(),
    )?;
    if let Err(error) = std::fs::write(secondary_qmi::SECONDARY_QMI_ENDPOINTS_STATE_FILE, payload) {
        eprintln!(
            "could not write {}: {error}",
            secondary_qmi::SECONDARY_QMI_ENDPOINTS_STATE_FILE
        );
    }

    if prepared.len() == 1 {
        let endpoint = &prepared[0];
        if let Err(error) = std::fs::write(
            secondary_qmi::SECONDARY_QMI_STATE_FILE,
            &endpoint.device_path,
        ) {
            eprintln!(
                "could not write {}: {error}",
                secondary_qmi::SECONDARY_QMI_STATE_FILE
            );
        }
    } else if let Err(error) = std::fs::remove_file(secondary_qmi::SECONDARY_QMI_STATE_FILE) {
        if error.kind() != std::io::ErrorKind::NotFound {
            eprintln!(
                "could not remove ambiguous {}: {error}",
                secondary_qmi::SECONDARY_QMI_STATE_FILE
            );
        }
    }
    Ok(())
}

async fn notify_ready(status: &str) {
    if std::env::var_os("NOTIFY_SOCKET").is_some() {
        let _ = tokio::process::Command::new("systemd-notify")
            .args(["--ready", &format!("--status={status}")])
            .status()
            .await;
    }
}

#[cfg(test)]
mod tests {
    use super::udev_rules;

    #[test]
    fn control_port_and_netdev_use_their_own_subsystems() {
        let rules = udev_rules("wwan0at2", Some("wwan1"));
        assert_eq!(rules.len(), 2, "{rules:?}");
        assert!(rules[0].contains(r#"SUBSYSTEM=="wwan""#), "{rules:?}");
        assert!(rules[0].contains(r#"KERNEL=="wwan0at2""#), "{rules:?}");
        assert!(rules[1].contains(r#"SUBSYSTEM=="net""#), "{rules:?}");
        assert!(rules[1].contains(r#"KERNEL=="wwan1""#), "{rules:?}");
        for rule in &rules {
            assert!(rule.contains(r#"ENV{ID_MM_PORT_IGNORE}="1""#), "{rule}");
        }
    }

    #[test]
    fn no_netdev_means_no_net_rule() {
        let rules = udev_rules("wwan0qmi1", None);
        assert_eq!(rules.len(), 1, "{rules:?}");
        assert!(!rules.iter().any(|rule| rule.contains(r#"KERNEL=="""#)));
    }

    #[test]
    fn rules_follow_observed_names() {
        let rules = udev_rules("wwan3qmi7", Some("wwan9"));
        assert!(rules[0].contains(r#"KERNEL=="wwan3qmi7""#));
        assert!(rules[1].contains(r#"KERNEL=="wwan9""#));
    }
}
